version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: 'symfony_sandbox_database'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-symfony_sandbox}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-symfony_sandbox}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  mailhog:
    image: mailhog/mailhog
    container_name: 'symfony_sandbox_mailhog'
    logging:
      driver: 'none'
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
